### ISSUE TITLE
Authentication does not use OAuth

### ISSUE THREAD

**Issue by justcool393** [justcool393/SnapshillBot#10]
In PRAW 4, and as of about two years ago, all API clients are supposed to use OAuth for requests. Migrating will allow us to make one request per second instead of per two seconds.

@hidde-jan I already have an API key and stuff set up. Until we migrate to PRAW 4, it'll be difficult to use it. See https://www.reddit.com/prefs/apps/

**Comment by hidde-jan** [comment]
My idea was to migrate to praw 4 as soon as I got the parallel requests working. Praw 4 also uses response headers to check how soon the next request can be made.

I'm currently working with gevent, but since we use 🐍 > 3.5, we could also use python's native coroutines. I don't know how they work yet tho, so sticking to gevent is my plan for now. I expect I'll have it done somewhere later this week. 

Verstuurd vanaf mijn iPhone

**Comment by justcool393** [comment]
Okay, awesome. Thanks for the work. :)

**Comment by hidde-jan** [comment]
Fixed with Gevent
